// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkZaFMWFmxd4iVptPIJJnUeefaWbBLaFY',
    appId: '1:92270589152:web:7451b0a5296b071c48cc85',
    messagingSenderId: '92270589152',
    projectId: 'mind-well-app-2c76f',
    authDomain: 'mind-well-app-2c76f.firebaseapp.com',
    storageBucket: 'mind-well-app-2c76f.firebasestorage.app',
    measurementId: 'G-YXYTXS38GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJXPer3DnClv71Vlyj0a8q4Z-pSOcUF-w',
    appId: '1:92270589152:android:20824066c24390d448cc85',
    messagingSenderId: '92270589152',
    projectId: 'mind-well-app-2c76f',
    storageBucket: 'mind-well-app-2c76f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBup0yE2dnBkax-AreKjOnvR-Z_FXdP-00',
    appId: '1:92270589152:ios:8c2c9b41e79a39ad48cc85',
    messagingSenderId: '92270589152',
    projectId: 'mind-well-app-2c76f',
    storageBucket: 'mind-well-app-2c76f.firebasestorage.app',
    iosBundleId: 'com.example.semesterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBup0yE2dnBkax-AreKjOnvR-Z_FXdP-00',
    appId: '1:92270589152:ios:8c2c9b41e79a39ad48cc85',
    messagingSenderId: '92270589152',
    projectId: 'mind-well-app-2c76f',
    storageBucket: 'mind-well-app-2c76f.firebasestorage.app',
    iosBundleId: 'com.example.semesterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkZaFMWFmxd4iVptPIJJnUeefaWbBLaFY',
    appId: '1:92270589152:web:b97518d75902e1aa48cc85',
    messagingSenderId: '92270589152',
    projectId: 'mind-well-app-2c76f',
    authDomain: 'mind-well-app-2c76f.firebaseapp.com',
    storageBucket: 'mind-well-app-2c76f.firebasestorage.app',
    measurementId: 'G-GPDGMEC9HE',
  );
}
